/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.outleet_tenis;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.PrintWriter;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Honorato
 */
public class CompraTenis extends javax.swing.JFrame {

    /**
     * Creates new form CompraTenis
     */
    public CompraTenis() {
        initComponents();
        camcpf();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        d3 = new javax.swing.JLabel();
        d4 = new javax.swing.JLabel();
        c2 = new javax.swing.JFormattedTextField();
        c3 = new javax.swing.JFormattedTextField();
        c4 = new javax.swing.JFormattedTextField();
        radiopix = new javax.swing.JRadioButton();
        radiocartao = new javax.swing.JRadioButton();
        radiodebito = new javax.swing.JRadioButton();
        radiodin = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        c5 = new javax.swing.JComboBox<>();
        d5 = new javax.swing.JLabel();
        d1 = new javax.swing.JLabel();
        d2 = new javax.swing.JLabel();
        c1 = new javax.swing.JFormattedTextField();
        d6 = new javax.swing.JLabel();
        csenha = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        campo_rua = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        campo_bairro = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        campo_cep = new javax.swing.JFormattedTextField();
        campo_num = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        campo_complemento = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        lblfrete = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        btncalc = new javax.swing.JButton();
        lblfrete1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        campo_cpf = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbquant = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        campo_nome = new javax.swing.JTextField();
        cmb = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cmbtam = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        precoL = new javax.swing.JLabel();
        precoL1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        vtotal = new javax.swing.JLabel();
        txtvalortot = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COMPRA DE PRODUTO");
        setAutoRequestFocus(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        d3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        d3.setText("COD - SEG");

        d4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        d4.setText("VAL");

        buttonGroup1.add(radiopix);
        radiopix.setText("Pix");
        radiopix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiopixActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiocartao);
        radiocartao.setText("Cartão Crédito");
        radiocartao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiocartaoActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiodebito);
        radiodebito.setText("Cartão de Débito");
        radiodebito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiodebitoActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiodin);
        radiodin.setText("Boleto");
        radiodin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiodinActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("FORMA DE PAGAMENTO");

        c5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        c5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c5ActionPerformed(evt);
            }
        });

        d5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        d5.setText("PARCELAS");

        d1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        d1.setText("NOME");

        d2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        d2.setText("N° CARTÃO");

        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        d6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        d6.setText("SENHA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(d1)
                        .addGap(18, 18, 18)
                        .addComponent(c1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(d2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(d6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(csenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(d3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(d4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(d5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(348, 348, 348)
                                .addComponent(radiodin)
                                .addGap(72, 72, 72)
                                .addComponent(radiopix))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(radiocartao)
                                .addGap(64, 64, 64)
                                .addComponent(radiodebito)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiocartao)
                    .addComponent(radiodebito)
                    .addComponent(radiodin)
                    .addComponent(radiopix))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d1)
                    .addComponent(d2)
                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d5)
                    .addComponent(c5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(c4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d4)
                    .addComponent(c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d3)
                    .addComponent(d6)
                    .addComponent(csenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("ENDEREÇO DE ENTREGA");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("RUA");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("BAIRRO");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("CEP");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("COMPLEMENTO");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("FRETE");

        lblfrete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblfrete.setText("0.00");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("N°");

        btncalc.setText("Calcular");
        btncalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcActionPerformed(evt);
            }
        });

        lblfrete1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblfrete1.setText("R$");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(campo_num, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel16)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(campo_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btncalc)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblfrete1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblfrete)))
                .addGap(36, 36, 36))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campo_rua, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel13)))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(campo_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(campo_cep, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel15)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel12)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(campo_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campo_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncalc)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblfrete)
                            .addComponent(lblfrete1))))
                .addGap(20, 20, 20))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(jLabel12)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(campo_rua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campo_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campo_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(74, Short.MAX_VALUE)))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Quantidade");

        cmbquant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));
        cmbquant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbquantActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("CPF");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nome Completo");

        cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Tenis");

        cmbtam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Tamanho");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("INFORMAÇÕES DO PEDIDO");

        precoL.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precoL.setText("0.00");

        precoL1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precoL1.setText("R$");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campo_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(campo_cpf)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(precoL1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(precoL)
                                .addGap(30, 30, 30)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(cmbtam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(cmbquant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campo_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbtam)
                    .addComponent(cmbquant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(precoL)
                    .addComponent(precoL1))
                .addGap(18, 18, 18))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("COMPRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("VALOR TOTAL");

        vtotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        vtotal.setText("0.00");

        txtvalortot.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtvalortot.setText("R$");

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("VOLTAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtvalortot)
                .addGap(31, 31, 31)
                .addComponent(vtotal)
                .addGap(35, 35, 35)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtvalortot)
                    .addComponent(vtotal)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
// TODO add your handling code here:
        int quant = Integer.parseInt((String) cmbquant.getSelectedItem());
        int parc = 0;
        double vtot = 0.00;
        double fret = Double.parseDouble(lblfrete.getText());
        String valor = "";
        List<String> compra = new ArrayList();
        
        if (fret == 0.00){
            System.out.println("vazio");
            JOptionPane.showMessageDialog(null,
                "PREENCHA O CAMPO FRETE", "WALLACE INFORMA:",
                JOptionPane.ERROR_MESSAGE);
           
        }else{
            
            if(radiocartao.isSelected()){
            
            parc = Integer.parseInt((String)c5.getSelectedItem());
            vtot = Double.parseDouble(precoL.getText());
            fret = Double.parseDouble(lblfrete.getText());
            vtot = quant * (vtot + (parc * 60) + fret);
            valor = String.valueOf(vtot);
            
            System.out.println(vtot);
            
        }         
            try {
                
                 File arquivoCSV = new File("C:\\Users\\Honorato\\Documents\\NetBeansProjects\\Outleet_Tenis\\src\\main\\java\\com\\mycompany\\outleet_tenis\\compra.csv");
                 String linhasDoArquivo = new String();           
                 Scanner leitor = new Scanner(arquivoCSV);
            
                 while (leitor.hasNext()){
                
                    linhasDoArquivo = leitor.nextLine();
                    compra.add(linhasDoArquivo);
                    
            }
                 
                 if (radiocartao.isSelected() || radiodebito.isSelected()){
                     compra.add(campo_nome.getText() + ";" + campo_cpf.getText() + ";" + cmb.getSelectedItem() + ";" + valor + ";" + c2.getText() + ";" + c5.getSelectedItem() + ";" + campo_rua.getText() + ", " + campo_num.getText()+ ", " + campo_bairro.getText() + ", " + campo_cep.getText() + ", " + campo_complemento.getText());
                 }
                 
                 else{
                     compra.add(campo_nome.getText() + ";" + campo_cpf.getText() + ";" + cmb.getSelectedItem() + ";" + valor + ";" + "---" + ";" + "---" + ";" + campo_rua.getText() + ", " + campo_num.getText()+ ", " + campo_bairro.getText() + ", " + campo_cep.getText() + ", " + campo_complemento.getText());
                 }
                
                PrintWriter pw = new PrintWriter(new File("C:\\Users\\Honorato\\Documents\\NetBeansProjects\\Outleet_Tenis\\src\\main\\java\\com\\mycompany\\outleet_tenis\\compra.csv"));
                
                StringBuilder sb=new StringBuilder();
                
                for (String lin : compra){
                    sb.append(lin);
                    sb.append("\r\n");
            }
                
                 pw.write(sb.toString());
                 pw.close(); 
                
                
            } catch (FileNotFoundException ex) {
                Logger.getLogger(CompraTenis.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        new Tela_Login().setVisible(false);
        
       List<String> tenis = new ArrayList();
        
        File arquivoCSVv = new File("C:\\Users\\Honorato\\Documents\\NetBeansProjects\\Outleet_Tenis\\src\\main\\java\\com\\mycompany\\outleet_tenis\\tenis.csv");
        
        try{          
            
            
            //variavel para receber as linhas por linhas 
            String linhasDoArquivo = new String();           
            Scanner leitor = new Scanner(arquivoCSVv);
            
            //Correr todas as linhas do arquivo
            while (leitor.hasNext()){
                
                linhasDoArquivo = leitor.nextLine();
                cmb.addItem(linhasDoArquivo);
                tenis.add(linhasDoArquivo);
            }
        }catch(FileNotFoundException e){   
        }
    }//GEN-LAST:event_formWindowActivated

    private void cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbActionPerformed
        // TODO add your handling code here:
        List<String> tenis = new ArrayList();
        List<String> preco = new ArrayList();
        String iten = (String) cmb.getSelectedItem();
        System.out.println(iten);
        int cont = 0, idp = 0;
        
        
        File arquivoCSV = new File("C:\\Users\\Honorato\\Documents\\NetBeansProjects\\Outleet_Tenis\\src\\main\\java\\com\\mycompany\\outleet_tenis\\tenis.csv");
        
        try{                      
            //variavel para receber as linhas por linhas 
            String linhasDoArquivo = new String();           
            Scanner leitor = new Scanner(arquivoCSV);
            
            //Correr todas as linhas do arquivo
            while (leitor.hasNext()){
                
                linhasDoArquivo = leitor.nextLine();
                tenis.add(linhasDoArquivo);
            }
            
            
            for (String x : tenis){
                
                if (x.equals(iten)){
                    idp = cont;
                }               
                cont += 1;               
            }
            System.out.println(idp);
            
        }catch(FileNotFoundException e){   
        }
        
        File arqCSV = new File("C:\\Users\\Honorato\\Documents\\NetBeansProjects\\Outleet_Tenis\\src\\main\\java\\com\\mycompany\\outleet_tenis\\preco_tenis.csv");
        
        try{                      
            //variavel para receber as linhas por linhas 
            String linhasDoArquivo = new String();           
            Scanner leitor = new Scanner(arqCSV);
            
            //Correr todas as linhas do arquivo
            while (leitor.hasNext()){
                
                linhasDoArquivo = leitor.nextLine();
                preco.add(linhasDoArquivo);
            }
            
            precoL.setText(preco.get(idp)); 
            
        }catch(FileNotFoundException e){   
        }
        
        if(!campo_rua.getText().equals("") && !campo_cep.getText().equals("") && !campo_num.getText().equals("") && !campo_bairro.getText().equals("")){
            
        comp();
            
        }
        
    }//GEN-LAST:event_cmbActionPerformed

    private void radiocartaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiocartaoActionPerformed
        // TODO add your handling code here:
         double fret = Double.parseDouble(lblfrete.getText());
        if (fret == 0.00){
            System.out.println("vazio");
            JOptionPane.showMessageDialog(null,
                "PREENCHA O CAMPO FRETE", "WALLACE INFORMA:",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
       
        c1.show(Boolean.TRUE);
        c2.show(Boolean.TRUE);
        c3.show(Boolean.TRUE); 
        c4.show(Boolean.TRUE);
        c5.enable(true);
        
    }//GEN-LAST:event_radiocartaoActionPerformed

    private void radiodebitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiodebitoActionPerformed
        // TODO add your handling code here:
        
        double fret = Double.parseDouble(lblfrete.getText());
        if (fret == 0.00){
            System.out.println("vazio");
            JOptionPane.showMessageDialog(null,
                "PREENCHA O CAMPO FRETE", "WALLACE INFORMA:",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        c1.show(Boolean.TRUE);
        c2.show(Boolean.TRUE);
        c3.show(Boolean.TRUE); 
        c4.show(Boolean.TRUE);
        c5.enable(false);
        
                if (campo_rua.getText().equals("") || campo_bairro.getText().equals("") || campo_cep.getText().equals("") || campo_num.getText().equals("") || campo_rua.getText().equals("")){
        
             JOptionPane.showMessageDialog(null,
                "ALERTA DE CAMPO VAZIO", "WALLACE INFORMA:",
                JOptionPane.ERROR_MESSAGE);
            
    } else{
                    
        lblfrete.setText("20.00");
        comp();
        
        }

    }//GEN-LAST:event_radiodebitoActionPerformed

    private void radiodinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiodinActionPerformed
        // TODO add your handling code here:
        
         double fret = Double.parseDouble(lblfrete.getText());
        if (fret == 0.00){
            System.out.println("vazio");
            JOptionPane.showMessageDialog(null,
                "PREENCHA O CAMPO FRETE", "WALLACE INFORMA:",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        c1.show(Boolean.FALSE);
        c2.show(Boolean.FALSE);
        c3.show(Boolean.FALSE);
        c4.show(Boolean.FALSE);
        c5.enable(false);

    }//GEN-LAST:event_radiodinActionPerformed

    private void radiopixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiopixActionPerformed
        // TODO add your handling code here:
        
        double fret = Double.parseDouble(lblfrete.getText());
        if (fret == 0.00){
            System.out.println("vazio");
            JOptionPane.showMessageDialog(null,
                "PREENCHA O CAMPO FRETE", "WALLACE INFORMA:",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        c1.show(Boolean.FALSE);
        c2.show(Boolean.FALSE);
        c3.show(Boolean.FALSE);
        c4.show(Boolean.FALSE);
        c5.enable(false);

    }//GEN-LAST:event_radiopixActionPerformed

    private void btncalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcActionPerformed
        // TODO add your handling code here:
        if (campo_rua.getText().equals("") || campo_bairro.getText().equals("") || campo_cep.getText().equals("") || campo_num.getText().equals("") || campo_rua.getText().equals("")){
        
             JOptionPane.showMessageDialog(null,
                "ALERTA DE CAMPO VAZIO", "WALLACE INFORMA:",
                JOptionPane.ERROR_MESSAGE);
            
    } else{
        lblfrete.setText("20.00");
            
       comp();
        
        }
    }//GEN-LAST:event_btncalcActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
        c1.setText(campo_nome.getText());
    }//GEN-LAST:event_c1ActionPerformed

    private void c5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c5ActionPerformed
        // TODO add your handling code here:
        
        comp();
        
    }//GEN-LAST:event_c5ActionPerformed

    private void cmbquantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbquantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbquantActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         new Tela_Principal().setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comp(){
        
        int quant = Integer.parseInt((String) cmbquant.getSelectedItem());
        int parc = 0;
        double vtot = 0.00;
        double frete = Double.parseDouble(lblfrete.getText());
        String valor = "";
        List<String> compra = new ArrayList();
        
         if(radiocartao.isSelected()){
            
            parc = Integer.parseInt((String)c5.getSelectedItem());
            vtot = Double.parseDouble(precoL.getText());
            frete = Double.parseDouble(lblfrete.getText());
            vtot = quant*(vtot + (parc * 60) + frete);
            valor = String.valueOf(vtot);
            
            vtotal.setText(valor);
            
         }else{
             
            vtot = Double.parseDouble(precoL.getText());
            frete = Double.parseDouble(lblfrete.getText());
            vtot = quant * (vtot + frete);
            valor = String.valueOf(vtot);
            
            vtotal.setText(valor);
         }
        
    }
    private void camcpf(){
        try {
            
            MaskFormatter mask_cpf = new MaskFormatter("###.###.###-##");
            mask_cpf.install(campo_cpf);
             MaskFormatter maskcep = new MaskFormatter("######-##");
            maskcep.install(campo_cep);
             MaskFormatter maskcartao = new MaskFormatter("####  ####  ####  ####");
            maskcartao.install(c2);
             MaskFormatter maskval = new MaskFormatter("##/##");
            maskval.install(c4);
             MaskFormatter maskseg = new MaskFormatter("###");
            maskseg.install(c3);
            
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro no preenchimento de campos ", "ERRO !", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompraTenis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompraTenis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompraTenis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompraTenis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompraTenis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JFormattedTextField c1;
    private javax.swing.JFormattedTextField c2;
    private javax.swing.JFormattedTextField c3;
    private javax.swing.JFormattedTextField c4;
    private javax.swing.JComboBox<String> c5;
    private javax.swing.JTextField campo_bairro;
    private javax.swing.JFormattedTextField campo_cep;
    private javax.swing.JTextField campo_complemento;
    private javax.swing.JFormattedTextField campo_cpf;
    private javax.swing.JTextField campo_nome;
    private javax.swing.JTextField campo_num;
    private javax.swing.JTextField campo_rua;
    private javax.swing.JComboBox<String> cmb;
    private javax.swing.JComboBox<String> cmbquant;
    private javax.swing.JComboBox<String> cmbtam;
    private javax.swing.JPasswordField csenha;
    private javax.swing.JLabel d1;
    private javax.swing.JLabel d2;
    private javax.swing.JLabel d3;
    private javax.swing.JLabel d4;
    private javax.swing.JLabel d5;
    private javax.swing.JLabel d6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblfrete;
    private javax.swing.JLabel lblfrete1;
    private javax.swing.JLabel precoL;
    private javax.swing.JLabel precoL1;
    private javax.swing.JRadioButton radiocartao;
    private javax.swing.JRadioButton radiodebito;
    private javax.swing.JRadioButton radiodin;
    private javax.swing.JRadioButton radiopix;
    private javax.swing.JLabel txtvalortot;
    private javax.swing.JLabel vtotal;
    // End of variables declaration//GEN-END:variables
}
